### ISSUE TITLE
Login not functioning

### ISSUE THREAD

**Issue by curlyjason** [OrigamiStructures/StudioManagerScratch#151]
When attempting to login, I get a badly formed class exception. The workaround is to turn off lines 144 - 146 in AppController, removing the creation of a CurrentUser object from the Auth User.
This code can be turned back on once I am logged in.

**Comment by curlyjason** [comment]
Potentially, check if there is a logged in user, and send the user to the login page if that is not true. Also need to protect the login and logout pages from this routine.

**Comment by curlyjason** [comment]
Made a fix in AppController::currentUser() to guard against the lack of an Auth user. This has solved the problem in the moment, but will need review when testing / establishing user management.

**Comment by dreamingmind** [comment]
working now
