### ISSUE TITLE
Editing addresses doesn't update disposition

### ISSUE THREAD

**Issue by curlyjason** [OrigamiStructures/StudioManagerScratch#31]
When you edit an address already linked to an incomplete disposition, the address does not update.

**Comment by dreamingmind** [comment]
Looking at this problem again:

While editing an address that is the current address-of-record in an evolving dispo does not automatically update the dispo, pushing the now updated address to the dispo again (as though it was a new choice) should update the dispo. Letting this stand as the 'normal' behavior would give a mechanism for users to get accurate records, even in this odd edge-case scenario, and would ruin the 'dispo editing' plan outlined in the 9/20/2016 comment above.

If this is an acceptable solution, probably no code changes are needed. We just need to verify that pushing the address to the dispo a second time updates the dispo.
