### ISSUE TITLE
Duplicate Edition names for an Artwork compresses into 1 in menus

### ISSUE THREAD

**Issue by dreamingmind** [OrigamiStructures/StudioManagerScratch#4]
This makes the duplicates invisible and inaccessible. There may be other problems too; tip of the iceberg?

**Comment by dreamingmind** [comment]
The issue of how to handle duplicate Edition names is a fairly serious one but the problem sighted here really is just the tip of an iceberg.

## The real issue is one of usability

How will artist's who think in terms of single, unique works adapt to the naming of editions. It is likely to feel like make-work. For that matter, how will they think about formats and their naming?

These were concepts that I understood while entering my initial data set, but I still struggled with what enter in these fields. I did write some defaults, so the artist can skip these if desired. It was these defaults that revealed the duplicate name problem. And it was my oft-repeated use of the defaults that pointed to the usability issues (though I rationalized my  past it at the time).

One general scheme that I've considered is creating a streamlined data entry path for artists who want to enter only unique works. The full data structure would be in place in case they later want to use Edition and Format features.

The question: What advantage does this Edition based strategy provide that single work systems don't? is a fair one. And we will need to have a compelling answer. I don't have one right now.

We will also need to match the ease of use of a single use system for artists who want to work that way or we will be abandoning all of that class of user.

## Not to ignore the issue...

But, whether we continue with default values as a streamlining aid, or receive values from users, we need to watch out for duplicate values and make sure the artist always know which edition (or format) they're operating on.

**Comment by curlyjason** [comment]
Is it possible to have editions be an optional add-on per piece? User optional?

**Comment by dreamingmind** [comment]
If I understand what your saying, possibly... But I'm not sure it would be a good idea.

To 'lack an edition' Artwork table would have to take on some new capabilities.

There are two major tasks we're doing:
1. recording the artwork made
2. tracking where and why individual works of art travel.

Currently, they way we 'join' these two tasks is through the Pieces table. Artworks table (and all the other layers) describe what is being made and how many there are. The actual transferable object is a record in the Pieces table. These records link to Dispositions (which describe where and why the Piece traveled.

To have an Artwork without an Edition means the Artwork must have Pieces (they don't currently). Then to optionally add editions means they must also have Pieces. Not to mention Formats.

This means at least two tables must act as 'the owner of traveling units'. All functionality and reporting must take this into account.

Right now, only Editions and Formats can have pieces. And Editions have what are technically 'virtual' pieces (they don't physically exist and can't get dispositions/travel). Only Format pieces travel/exist. Edition pieces are a pool of virtual elements that can be assigned to Formats.

This means each layer fulfills one role without overlap.

I'm not sure how we make Editions optional and maintain the focus of the layers. We'd have to re-conceive the basic schema I think. But I'm not sure how.

My strategy so far can be seen in the creation of Unique works. These would be something like paintings, sketches, or sculptures. I have a streamlined input path that automatically generates all the necessary layers to make an Artwork with one Edition, one Format, and one Piece.

This way, it acts like every other artwork, like every other edition, like every other format, and every other piece. We can always route it to a simplified UX because of data (`type = EDITION_UNIQUE`) and methods (`isFlat()`) in the entities.
