### ISSUE TITLE
Cache naming classes needed

### ISSUE THREAD

**Issue by dreamingmind** [OrigamiStructures/StudioManagerScratch#80]
I'm also experimenting with a Trait in the EditionStackComponent that encapsulates the caching tools for the stack. This seems like a useful approach in general. It replaces cache name assembly code (which gets sprinkled all around) with cache name getter methods. As an overall cache naming scheme comes together, a hierarchy of cache classes might emerge.

**Comment by dreamingmind** [comment]
This will replace nightmares like:

```
Cache::delete("get_default_artworks[_{$piece->format['edition']['artwork']['id']}_]", 'artwork');
```
with things like:
```
$this->ArtCache->delete($piece->format['edition']['artwork']['id']);
```
The classes can be pretty simple. They rely on access to a property that identifies the cache configuration to use and the private key generation method that centralized that process.

This test exists as a Trait but that might not be the best. If it stays a trait the configuration property would have to come from the parent class, not the trait.

<img width="677" alt="screen shot 2018-09-04 at 9 30 03 am" src="https://user-images.githubusercontent.com/1307216/45044627-7b143300-b025-11e8-8ac9-4ab66e2586f9.png">

**Comment by dreamingmind** [comment]
The main reason I haven't gone ahead and written what seems like a fairly simple system is:

Admin users that have privileges to manage multiple artists would—in a simple case—write caches with the individual artist ids in the keys. This allows SysAdmins to go and kill all an artist's caches if some problem arises. But how to kill all an Admins caches... 

In general, this cache-key problem needs some thought. Not only how to key them for easy management but how to make use of the 'group' feature. That build in feature might make cache clearing after record edits much easier but we'd have to be able to set it dynamically rather than in a bootstrap config (which would make all users caches members of the same group :-|

**Comment by dreamingmind** [comment]
Even once the cache management strategy (probably based on the 'group' system) is resolved, the actual keys will need to be designed. I'm still leaning toward keys that use the artist ID. That will let us kill all of a users caches as a bug resolution step. It could also ease development by letting the current cached data be swept clean with a call or as a default when debugging is enabled.

If we go ahead with a flat-record query and caching strategy, and also cache each flat record set separately we could do something like:

```
// if the top level Artwork record is ID = 972
$dispostion_key =  "xxxxartist-idxxxxxx-927-dispositions";
$editions_key =  "xxxxartist-idxxxxxx-927-editions";
$formats_key =  "xxxxartist-idxxxxxx-927-formats";
// and the caches configs could make flat or nested directories
```

As has been mentioned, making Artwork->id available at every level is critical.

The same overall patter would be used for cached Member data and other data as needed.

If an artist manager was using the system and needed tech support we could then walk through all their artists, clear complete cache sets.

This still doesn't address Element caching. I'm not clear enough on the system architecture to know what value we can get from that feature.

There is still an idea on the table to array-ify all the flat sets in a single cache. This would make a single read. But testing suggests that built-in query caches are faster than hand saved caches. Presumably this is because the native version uses SPLFixedArray (which is supposed to be smaller and faster). I'm moving toward setting up version of the system to test the alternatives. Doing so should also force me to properly encapsulate the code.

**Comment by curlyjason** [comment]
If all of a users caches were killed, what would be their performance impact. Huge? Minor? For how long? 

It seems like you’re discussing a pretty extensive overlay on an inbuilt system. How much bang for this coding buck?

**Comment by dreamingmind** [comment]
This is being rewritten into a new, updated issue. Many of the questions here have been decided.
